version: "2"

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: Build hugo
    cmds:
      - hugo
  new_post:
    desc: create new post
    cmds:
      - ./script/new_post.sh
    silent: true
  serve:
    desc: start local srever
    cmds:
      - docker run --rm -it -p 1313:1313 -v $(pwd):/src klakegg/hugo:0.74.2-ext-alpine serve -D
  deploy:
    desc: start deploy
    deps:
      - build
    cmds:
      - npx firebase deploy
  serve_gitpod:
    desc: start local server on Gitpod
    cmds:
      - ./script/serve_on_gitpod.sh
