name: Lint
on: [push]

jobs:
  markdown:
    name: Lint markdown
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "README.md content/**/*.md"
          config_file: ".markdownlint.json"
